#!/usr/bin/env ruby

require 'optparse'
dirname = File.dirname(__FILE__)
Dir['*.rb'].each do |rb_file|
  require File.join(dirname, rb_file)
end

unless ARGV.empty?
  OptionParser.new do |opts|
    opts.on("-d", "--detailed", "Detailed Output") do |d|
      options[:detailed] = d
    end

    opts.on("-v", "--verbose", "Verbose Output") do |v|
      options[:verbose] = v
    end
  end.parse!
end

ARGV.clear

Sim::Scheduler.new.run!